### ISSUE TITLE
App crashed as soon as node started running (v0.1.0-alpha.3)

### ISSUE THREAD

**Issue by cyptsd** [mimblewimble/grin-gui#83] opened 2024-01-21 15:54 UTC
The node downloaded the chain ok but as soon as it was ready the app crashed. It now crashes as soon as it connects to peers.

 - OS: Windows 10 Home 22H2
 - Version v0.1.0-alpha.3

**Comment by yeastplume** [comment] 2024-02-08 14:46
Likely duplicate of #73

**Closed by yeastplume** 2024-02-08 14:46 UTC
Labels: bug
